#!/bin/bash
if [[ "$1" == "--supplies" ]]; then
	echo "b bold link a img ul u i italics !dark !light"
else
	case "$1" in
		b|bold)
			echo "<b>${!#}</b>"
			;;
		a|link)
			echo "<a href=\"$2\">${!#}</a>"
			;;
		i|italics)
			echo "<i>${!#}</i>"
			;;
		img)
			echo "<img src=\"${!#}\" ${@:2:$#-2}>"
			;;
		ul|u)
			echo "<u>${!#}</u>"
			;;
	esac
	# Styles
	case "$1" in
		!dark)
			if [[ ${!#} == "--style" ]]; then
				style="
				.dark {
					background-color: #121212;
					color: #e4e4e4;
					font-family: system-ui, sans-serif;
					line-height: 1.6;
				}
			.dark body {
				background-color: #121212;
				color: #e4e4e4;
				font-family: system-ui, sans-serif;
				line-height: 1.6;
				margin: 0;
				padding: 20px;
			}

		/* Headings */
		.dark h1,
		.dark h2,
		.dark h3,
		.dark h4,
		.dark h5,
		.dark h6 {
			color: #ffffff;
			margin-top: 1.4em;
		}

	/* Links */
	.dark a {
		color: #4da3ff;
		text-decoration: none;
	}
		
		.dark a:hover {
			text-decoration: underline;
			color: #7ab8ff;
		}
		
		/* Paragraphs */
		.dark p {
			margin-bottom: 1em;
		}
		
		/* Lists */
		.dark ul,
		.dark ol {
			margin-left: 1.5em;
		}
				"
				echo "$style"
			else
				echo "dark"
			fi
			;;
		!light)
			if [[ ${!#} == "--style" ]]; then
				style="
				/* Headings */
				.light h1,
				.light h2,
				.light h3,
				.light h4,
				.light h5,
				.light h6 {
					color: #111111;
					margin-top: 1.4em;
				}

			/* Links */
			.light a {
				color: #0066cc;
				text-decoration: none;
			}

		.light a:hover {
			text-decoration: underline;
			color: #004999;
		}

	/* Paragraphs */
	.light p {
		margin-bottom: 1em;
	}

/* Lists */
.light ul,
.light ol {
	margin-left: 1.5em;
}
.light {
	background-color: #ffffff;
	color: #222222;
	font-family: system-ui, sans-serif;
	line-height: 1.6;
}
				"
				echo "$style"
			else
				echo "light"
			fi
			;;
			
	esac
fi
